version: 2
jobs:
   build:
     docker:
       - image: mrivingt/testrail
       auth:
       username: mrivingt
       password: Lexington40
     steps:
       - checkout
       - run: echo "hello world"
